apiVersion: v1
kind: Service
metadata:
  name: {{ include "levis-nginx" . }} # Or whatever name your chart generates
  labels:
    {{- include "levis-nginx.labels" . | nindent 4 }}
spec:
  type: LoadBalancer # <--- CHANGE THIS LINE!
  ports:
    - port: 80       # The port the Load Balancer will listen on externally (e.g., http://your-lb-ip:80)
      targetPort: 80 # The port your Nginx container is listening on internally (default Nginx port)
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "levis-nginx.name" . }} # Your deployment's app label
    app.kubernetes.io/instance: {{ .Release.Name }} # Your deployment's instance label
