apiVersion: v1
kind: Service
metadata:
  name: {{ include "levis-nginx.fullname" . }}
  labels:
    {{- include "levis-nginx.labels" . | nindent 4 }}
spec:
  # Conditionally set the service type based on .Values.ingress.enabled
  type: {{ if .Values.ingress.enabled }}ClusterIP{{ else }}LoadBalancer{{ end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }} # This should match your Nginx container's listening port
      protocol: TCP
      name: http
  selector:
    {{- include "levis-nginx.selectorLabels" . | nindent 4 }}
